pcall(require, 'impatient')

require('config.editor')
local l = require('config.languages')
l.viml()
l.yaml()
l.json()
l.lua()
l.markdown()
l.go()
l.terraform()
l.rust()
l.typescript()
l.zig()
require('config.format').load()
