--- Module settings, store a settings table cross all neovim configs. This
--- module reads Home Manager managed settings from ~/.config/crows/settings.json
--- and overrides the default settings defined here.
--- Choose json format for easily generated by Nix.

---@class Settings
---@field theme ThemeSettings
---@field use_global_statusline boolean
---@field hide_command_line boolean
---@field use_gofumpt boolean
---@field agent string

---Theme must support dynamic switching dark/light mode based on system settings.
---@class ThemeSettings
---@field name 'rose-pine' | 'zenbones'

---@type Settings
local M = {
  theme = { name = 'rose-pine' },
  use_global_statusline = false,
  hide_command_line = false,
  use_gofumpt = true,
  agent = 'opencode',
}

local function get_settings_path()
  local config_home = vim.fs.dirname(vim.fn.stdpath('config'))
  return vim.fs.normalize(vim.fs.joinpath(config_home, 'crows', 'settings.json'))
end

-- Load Home Manager settings from ~/.config/crows/settings.json
local local_settings_path = get_settings_path()
local local_settings_file = io.open(local_settings_path, 'r')
if local_settings_file then
  local content = local_settings_file:read('*a')
  local local_settings_ok, cfg = pcall(vim.fn.json_decode, content)
  local_settings_file:close()

  if local_settings_ok and type(cfg) == 'table' then
    M = vim.tbl_deep_extend('force', M, cfg)
  else
    vim.notify(
      ('Failed to parse settings file: %s'):format(local_settings_path),
      vim.log.levels.ERROR,
      { title = 'config.settings' }
    )
  end
end

return M
