-- Nanozuki Vim Config
require("util/plugin")
require("basic")
require("colorscheme")
require("lsp")
require("complete")
require("edit")
require("indent")
require("lang")
require("search")
require("view")
