"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 2_000

[character]
success_symbol = '[»](bold purple)'
error_symbol = '[»](bold red)'

[directory]
truncation_length = 10
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[git_metrics]
added_style = "green"
deleted_style = "red"
format = '([+$added]($added_style))([-$deleted]($deleted_style)) '
disabled = false

[status]
disabled = false

# languages
[golang]
symbol = ' '
[lua]
disabled = true

# disabled modules
[aws]
disabled = true
[gcloud]
disabled = true
